[build]
  command = "prisma generate && npm run build"

[dev]
  functions = "dist/functions"

[functions]
  external_node_modules = ["express", "@prisma/client", ".prisma"]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"