[build]
  functions = "dist/functions"
  command = "npm run build"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  to = "/.netlify/functions/api/:splat"
  from = "/api/*"
  force = true
  status = 200