[build]
  publish = "dist"
  command = "npm run build"
  functions = "dist/functions"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  directory = "dist/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
