name: Cron Job

on:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  fetch:
    name: Update LeaderBoard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20
      - run: npm install
      - run: npm run generate:leaderboard
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          SERVER_URL: ${{ secrets.SERVER_URL }}

  trigger:
    needs: fetch
    name: Trigger another workflow and wait
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: Resourcio-Community
          repo: apertre
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          workflow_file_name: main.yml
